version: '3.8'

services:

  mysql_db_accounts:
    container_name: mysql_db_accounts
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data_db_accounts:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: db_accounts
    extends:
      file: common-compose.yml
      service: microservice-db-config
    networks:
      - accounts-net

  mysql_db_loans:
    container_name: mysql_db_loans
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data_db_loans:/var/lib/mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: db_loans
    extends:
      file: common-compose.yml
      service: microservice-db-config
    networks:
      - loans-net

  mysql_db_cards:
    container_name: mysql_db_cards
    image: mysql:8.0.32
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - mysql_data_db_cards:/var/lib/mysql
    ports:
      - "3308:3306"
    environment:
      MYSQL_DATABASE: db_cards
    extends:
      file: common-compose.yml
      service: microservice-db-config
    networks:
      - cards-net

  accounts:
    container_name: accounts
    image: pblgllgs/accounts-sb3:v2
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_APPLICATION_NAME: accounts
    depends_on:
      mysql_db_accounts:
        condition: service_healthy
    extends:
      file: common-compose.yml
      service: microservice-eurekaserver-config
    networks:
      - accounts-net

  loans:
    container_name: loans
    image: pblgllgs/loans-sb3:v2
    restart: always
    ports:
      - "8090:8090"
    environment:
      SPRING_APPLICATION_NAME: loans
    depends_on:
      mysql_db_loans:
        condition: service_healthy
    extends:
      file: common-compose.yml
      service: microservice-eurekaserver-config
    networks:
      - loans-net

  cards:
    container_name: cards
    image: pblgllgs/cards-sb3:v2
    restart: always
    ports:
      - "9000:9000"
    environment:
      SPRING_APPLICATION_NAME: cards
    depends_on:
      mysql_db_cards:
        condition: service_healthy
    extends:
      file: common-compose.yml
      service: microservice-eurekaserver-config
    networks:
      - cards-net

  configserver:
    container_name: configserver
    image: pblgllgs/configserver-sb3:v2
    restart: always
    environment:
      SPRING_APPLICATION_NAME: configserver
    healthcheck:
      test: "curl --fail --silent localhost:8071/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "8071:8071"
    extends:
      file: common-compose.yml
      service: microservice-base-config

  eurekaserver:
    container_name: eurekaserver
    image: pblgllgs/eurekaserver-sb3:v2
    restart: always
    environment:
      SPRING_APPLICATION_NAME: eurekaserver
    healthcheck:
      test: "curl --fail --silent localhost:8070/actuator/health/readiness | grep UP || exit 1"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "8070:8070"
    extends:
      file: common-compose.yml
      service: microservice-configserver-config

volumes:
  mysql_data_db_accounts:
    external: false
  mysql_data_db_loans:
    external: false
  mysql_data_db_cards:
    external: false

networks:
  spring:
    driver: bridge
  accounts-net:
    driver: bridge
  cards-net:
    driver: bridge
  loans-net:
    driver: bridge